
public class TriggerUtils
{
	/*
	*	@description Return the values of a specific sObject field.
	*	
	* 	Note:	sObject - all standard and custom objects, 
	*		Object - all primitive data types Decimal, String, Integer, Boolean
	*/
    	public static Set<Object> getFieldValue (List<sObject> sObjects, String fieldName)
	{
		/*
		*	TODO: Iterate over all 'sObjects' and return dynamically the values of the 'fieldName' field. 
		*/
		return null;
	}
}
